# Generated by Django 4.2 on 2024-09-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
