# Generated by Django 4.2 on 2024-09-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aricle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
